export const TableData = [
    {
        full_name: "User A",
        email: "user_a@mail.com",
        contact: "9826543210",
        address: "Address Location A",
    },
    {
        full_name: "User B",
        email: "user_b@mail.com",
        contact: "9826543211",
        address: "Address Location B",
    },
    {
        full_name: "User C",
        email: "user_c@mail.com",
        contact: "9826543212",
        address: "Address Location C",
    },
    {
        full_name: "User D",
        email: "user_d@mail.com",
        contact: "9826543213",
        address: "Address Location D",
    },
    {
        full_name: "User E",
        email: "user_e@mail.com",
        contact: "9826543214",
        address: "Address Location E",
    },
    {
        full_name: "User F",
        email: "user_f@mail.com",
        contact: "9826543215",
        address: "Address Location F",
    },
    {
        full_name: "User G",
        email: "user_g@mail.com",
        contact: "9826543216",
        address: "Address Location G",
    },
    {
        full_name: "User H",
        email: "user_h@mail.com",
        contact: "9826543217",
        address: "Address Location H",
    },
    {
        full_name: "User I",
        email: "user_i@mail.com",
        contact: "9826543218",
        address: "Address Location I",
    },
    {
        full_name: "User J",
        email: "user_j@mail.com",
        contact: "9826543219",
        address: "Address Location J",
    },
    {
        full_name: "User K",
        email: "user_k@mail.com",
        contact: "9826543220",
        address: "Address Location K",
    },
    {
        full_name: "User L",
        email: "user_l@mail.com",
        contact: "9826543221",
        address: "Address Location L",
    },
    {
        full_name: "User M",
        email: "user_m@mail.com",
        contact: "9826543222",
        address: "Address Location M",
    },
    {
        full_name: "User N",
        email: "user_n@mail.com",
        contact: "9826543223",
        address: "Address Location N",
    },
    {
        full_name: "User O",
        email: "user_o@mail.com",
        contact: "9826543224",
        address: "Address Location O",
    },
    {
        full_name: "User P",
        email: "user_p@mail.com",
        contact: "9826543225",
        address: "Address Location P",
    },
    {
        full_name: "User Q",
        email: "user_q@mail.com",
        contact: "9826543226",
        address: "Address Location Q",
    },
    {
        full_name: "User R",
        email: "user_r@mail.com",
        contact: "9826543227",
        address: "Address Location R",
    },
    {
        full_name: "User S",
        email: "user_s@mail.com",
        contact: "9826543228",
        address: "Address Location S",
    },
    {
        full_name: "User T",
        email: "user_t@mail.com",
        contact: "9826543229",
        address: "Address Location T",
    },
    {
        full_name: "User U",
        email: "user_u@mail.com",
        contact: "9826543230",
        address: "Address Location U",
    },
    {
        full_name: "User V",
        email: "user_v@mail.com",
        contact: "9826543231",
        address: "Address Location V",
    },
    {
        full_name: "User W",
        email: "user_w@mail.com",
        contact: "9826543232",
        address: "Address Location W",
    },
    {
        full_name: "User X",
        email: "user_x@mail.com",
        contact: "9826543232",
        address: "Address Location X",
    },
    {
        full_name: "User Y",
        email: "user_y@mail.com",
        contact: "9826543233",
        address: "Address Location y",
    },
    {
        full_name: "User Z",
        email: "user_z@mail.com",
        contact: "9826543234",
        address: "Address Location Z",
    },
    {
        full_name: "User One",
        email: "user_one@mail.com",
        contact: "9826543235",
        address: "Address Location One",
    },
    {
        full_name: "User Two",
        email: "user_two@mail.com",
        contact: "9826543236",
        address: "Address Location Two",
    },
    {
        full_name: "User Three",
        email: "user_three@mail.com",
        contact: "9826543237",
        address: "Address Location Three",
    },
    {
        full_name: "User Four",
        email: "user_four@mail.com",
        contact: "9826543238",
        address: "Address Location Four",
    },
]